### PR TITLE
Adds pip-review and pipupgrade support

### LINKED ISSUE #304: Pip modules update
## I want to suggest a new step
Topgrade currently updates pip itself. My suggestion is to add an optional feature to update installed modules, through `pip-review`.
### Which tool is this about? Where is its repository?
pip-review https://github.com/jgonggrijp/pip-review

### Which operating systems are supported by this tool?
All where python/pip works - both tools are pip modules

### What should Topgrade do to figure out if the tool needs to be invoked?
Same as pip.
`pipupgrade` should be explicited declared on command-line or `topgrade.toml`
**Maybe** add a message just like `winget` is "disabled by default" when running on Windows.

### Which exact commands should Topgrade run?

`pip-review -a -C`

```
  --auto, -a            Automatically install every update found
  --continue-on-fail, -C
                        Continue with other installs when one fails

```

### PR DESCRIPTION
**Pull request by DottoDev**
Closes #304 
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Review by luciodaou — CHANGES_REQUESTED** [review]
It's failing, when I try to run after building and uncommenting the enable_pip_review flag inside linux section:

```
lucio in topgrade-dev/target/debug
➜  ./topgrade --config ../../config.example.toml --only pip_review
ERROR Failed to deserialize ../../config.example.toml
ERROR failed to load configuration: unknown field `enable_pip_review`, expected one of `yay_arguments`, `aura_aur_arguments`, `aura_pacman_arguments`, `arch_package_manager`, `show_arch_news`, `garuda_update_arguments`, `trizen_arguments`, `pikaur_arguments`, `pamac_arguments`, `dnf_arguments`, `apt_arguments`, `enable_tlmgr`, `redhat_distro_sync`, `rpm_ostree`, `emerge_sync_flags`, `emerge_update_flags` for key `linux` at line 120 column 1
```
Update:
On the config file, I tried moving the flag outside of Linux section, as the only flag in the file, failed too:
```
lucio in topgrade-dev/target/debug
➜  ./topgrade --config ../../config.example.toml --only pip_review
ERROR Failed to deserialize ../../config.example.toml
ERROR failed to load configuration: invalid type: string "PipReview", expected struct PipReview for key `enable_pip_review` at line 1 column 20
```

Trying to use `"PipReview"` or `PipReview` instead of `true` didn't work either.

**Comment by luciodaou** [comment]
I tried some things, like changing the flags to bool, but it gave me errors way too complex for me. Rust syntax ain't easy like Python... 🤣

**Comment by luciodaou** [comment]
@DottoDev , managed to make it work after some trial and error. The problem is that the code is looking for this on the config file:
```
[enable_pip_review]
enable = true
```

The example file and error messages says different things about it. The example config.toml file says `enable_pip_review = true` should be inside `[Linux]` section, but that gives the errors I mentioned on my first reply (https://github.com/topgrade-rs/topgrade/pull/316#pullrequestreview-1252671696).

**Comment by luciodaou** [comment]
Also, after making it work, I got a build error on one of the modules, but topgrade detected it as running OK:

image

**Comment by DottoDev** [comment]
Damm it I hate it when tools use different exit codes 😂

**Comment by DottoDev** [comment]
@luciodaou Sorry for the late response, could you check that out

**Review by luciodaou — APPROVED** [review]
Working!

image

**Review by luciodaou — APPROVED** [review]

**Comment by luciodaou** [comment]
On one of my WSL distros, I have both pip-review and pipupgrade installed, so I don't need both on topgrade.

So I configured my `topgrade.toml` file like this:
```
[python]
enable_pip_review = true   ###disabled by default
enable_pipupgrade = false   ###disabled by default
```

Yet, it still enables pipupgrade:
image

If I comment out the pipupgrade line, it still runs:
image

Disabling both by comment:
image

Disabling both by the flags:
image

It seems that pipupgrade is piggybacking on pip-review flag.

**Pull request merged**
