### PR TITLE
Bump the `bug-fixes` branch to match `master`

### PR DESCRIPTION
**Pull request by pan93412**
* Update README.md

* Update release-cross.yml

* Update release.yml

* style(self_update): Run cargo fmt (#108)

The commit 9105a8aac is not formatted, which breaks the CI check.

Co-authored-by: Thomas Schönauer <37108907+DottoDev@users.noreply.github.com>

* Clap dependencie change

* Revert clap changes

Co-authored-by: pan93412 <pan93412@gmail.com>

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles (`cargo build`)
- [ ] The code passes rustfmt (`cargo fmt`)
- [ ] The code passes clippy (`cargo clippy`)
- [ ] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by pan93412** [comment]
@DottoDev

**Comment by 0xMRTT** [comment]
@pan93412 could you add me as co-author ?

**Comment by pan93412** [comment]
Seems unnecessary to make this PR. @DottoDev Could you help me rebase `bug-fixes` on your side? Thanks!

**Comment by DottoDev** [comment]
I'm currently not on my machine, will do asap.

**Pull request closed without merging**
