### PR TITLE
Improve help prompt value names

### PR DESCRIPTION
**Pull request by tranzystorek-io**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by pan93412** [comment]
Excellent PR! Visual Changes:

截圖 2022-11-05 下午8 04 27

截圖 2022-11-05 下午8 04 39

**Review by pan93412 — APPROVED** [review]

**Comment by tranzystorek-io** [comment]
the custom-command logic could probably use some improvement, as it seems to always run all the items from custom commands instead of just the selected ones

**Review by DottoDev — APPROVED** [review]

**Comment by DottoDev** [comment]
Could you change the branch to the bug-fixes branch.

**Comment by tranzystorek-io** [comment]
Done

**Pull request merged**
