### PR TITLE
fix: update fedora

### PR DESCRIPTION
**Pull request by 0xMRTT**
Fedora 36 instead of Fedora 29

### CODE REVIEW

**Comment by pan93412** [comment]
I found that such this change is unnecessary – this is for test, and won't be a part of the upgrade process.

**Comment by 0xMRTT** [comment]
So, should i upgrade all distro release or not ?

**Comment by pan93412** [comment]
> So, should i upgrade all distro release or not ?

As this is for test, I think this part is not really important to waste time on updating them. However, I think the current PRs can leave as it is – we don't need to close them.

**Comment by DottoDev** [comment]
> I found that such this change is unnecessary – this is for integration test, and won't be a part of the upgrade process.

I'm still wondering if our integration tests are even useful.

**Comment by pan93412** [comment]
> > I found that such this change is unnecessary – this is for integration test, and won't be a part of the upgrade process.
> 
> I'm still wondering if our integration tests are even useful.

How about disabling `codecov` first? The notifications and warnings are really annoying, and the codebase has just a few of tests.

**Comment by 0xMRTT** [comment]
Yes, codecov is very annoying

**Comment by DottoDev** [comment]
Is disabled
Will be enabled when their are tests that work

**Pull request closed without merging**
