### PR TITLE
Add garuda-update

### PR DESCRIPTION
**Pull request by jstelzer**
if garuda-update is in our path use that instead of directly calling pacman/paru/powerpill. There's more stuff the update script does that you're just asking for problems if you upgrade partially.

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself
    - [x] I also tested that Topgrade skips the step where needed

I created a feature request here:
https://github.com/topgrade-rs/topgrade/issues/226

### CODE REVIEW

**Review by DottoDev — APPROVED** [review]

**Review by DottoDev — CHANGES_REQUESTED** [review]
Please format it first before this PR can be merged.

**Comment by jstelzer** [comment]
Sorry if it's dense, but what do you want WRT format? Just rustfmt? Other than that I merged in dev (i based the original patch off of master due to not knowing your workflow).

**Comment by jstelzer** [comment]
Sorry if it's dense, but what do you want WRT format? Just rustfmt? Other than that I merged in dev (i based the original patch off of master due to not knowing your workflow).

**Review by DottoDev — APPROVED** [review]

**Comment by DottoDev** [comment]
Jup, was just about rust Mt and clippy warnings

**Comment by jstelzer** [comment]
danke schoen

**Pull request merged**
