### PR TITLE
Adding .vscode/settings.json to .gitignore

### PR DESCRIPTION
**Pull request by niStee**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] I have read `CONTRIBUTING.md`
- [ ] The code compiles (`cargo build`)
- [ ] The code passes rustfmt (`cargo fmt`)
- [ ] The code passes clippy (`cargo clippy`)
- [ ] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
 
## For new steps
- [ ] *Optional:* Topgrade skips this step where needed
- [ ] *Optional:* The `--dry-run` option works with this step
- [ ] *Optional:* The `--yes` option works with this step if it is supported by 
  the underlying command

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by niStee** [comment]
Either adding .vscode/settings.json to .gitignore or including cargo.toml to .vscode/settings.json.

**Comment by SteveLauC** [comment]
I tend to remove the `.vscode` file and git ignore it, those editor config file should not be committed to the repo.


BTW, it seems that the changes in this PR are duplicate with the ones in #712?

**Comment by SteveLauC** [comment]
> I tend to remove the .vscode file and git ignore it

Done in #715

**Comment by niStee** [comment]
> > I tend to remove the .vscode file and git ignore it
> 
> Done in #715

I'm not sure you really want to do this. I am thinking of the launch.json, tasks.json and topgrade.code-snippets from the repository. They are nice to have.

**Comment by niStee** [comment]
> I tend to remove the `.vscode` file and git ignore it, those editor config file should not be committed to the repo.
> 
> BTW, it seems that the changes in this PR are duplicate with the ones in #712?

Yeah, added it to the wrong branch. It's now resolved.

**Comment by SteveLauC** [comment]
> I'm not sure you really want to do this. I am thinking of the launch.json, tasks.json and topgrade.code-snippets from the repository. They are nice to have.

Well, I believe both options have their own pros and cons, and indeed, this question is controversial and not conclusive, you can see there are tons of [discussions](https://stackoverflow.com/q/32964920/14092446) on it.

For a shared project, I tend to not commit them to keep the repo clean. (Personal preference)

**Pull request closed without merging**
