### PR TITLE
Changes version requirements to latest path of minor version

### PR DESCRIPTION
**Pull request by DottoDev**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by GideonBear** [comment]
Hey @s34m, what was the reasoning for this? I want to either revert this, or enforce this consistently.

**Comment by s34m** [comment]
The reason was simply to have the latest patch version of the used minor version while not having to manually update every time a new patch version is released.

**Comment by GideonBear** [comment]
> The reason was simply to have the latest patch version of the used minor version while not having to manually update every time a new patch version is released.

For clarity: `1.2.3` does not main the same as `=1.2.3`, but [the same as](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#default-requirements) `^1.2.3`, which is semver-versioning (e.g. `0.1.0` -> `0.1.1`, `1.0.0` -> `1.1.0`), while tilde-versioning only allows patch updates (`0.1.0` -> `0.1.1`, `1.0.0` -> `1.0.1`)

My question is why you chose tilde-versioning over caret-versioning (the default)? Or were you unaware that caret-versioning was the default? (If you want to do the least manual updating, caret-versioning makes more sense)

**Comment by s34m** [comment]
That's true but the intend was to still keep the same minor version, and only update the patch vetsion, to have the least amount of maintenance, which made sense at this point in time for me.

**Pull request merged**
