### PR TITLE
Quote arguments when executing in a shell

### LINKED ISSUE #107: tmux + ssh + fish breaks. $SHELL gets evaluated locally / escaping problems?
**What did you expect to happen?**

Executing my upgrades for other machines works, unless I start using them inside tmux.

Having them as a dry-run exposes (for example):
`/usr/bin/ssh -t flexo env TOPGRADE_PREFIX=flexo $SHELL -lc topgrade`

**What actually happened?**
The remote side gives back an error:
```
env: ‘/usr/local/bin/fish’: No such file or directory
```

But of course that cannot be executed like that: Although locally there is a `/usr/local/bin/fish` - no such thing exists remotely. The remote shell would be `/usr/bin/fish` (and is set as a default anyway).

So I guess `$SHELL` shouldn't be evaluated **locally** - so if I escape it manually (on the commandline) to be...

```
/usr/bin/ssh -t flexo env TOPGRADE_PREFIX=flexo '$SHELL' -lc topgrade
```

(pay attention to the single quotes around `$SHELL`)
... it works.

Now another error occurs if we have the `yes` flag activated, as it tries to run, but fails being unable to parse the commandline correctly. Weird.

Again, if I escape the given commandline to:

(Before)
```
/usr/bin/ssh -t flexo env TOPGRADE_PREFIX=flexo $SHELL -lc topgrade -y
```

(After)
```
/usr/bin/ssh -t flexo env TOPGRADE_PREFIX=flexo '$SHELL' -lc topgrade\ -y
```

it works.

**Additional details:**

*Which operating system or Linux distribution are you using?*
    macOS, from here trying to connect to multiple Linux hosts of different flavors. They all behave the same.
**How did you install Topgrade?**
    * Manually downloaded and placed in /usr/local/bin (linux) or ~/bin/topgrade (macos)
    * Installting via Homebrew
    * Manually compiling

Run topgrade --dry-run to see which commands Topgrade is running. If the command seems wrong and you know why pleaes tell us so.
If the command seems fine try to run it yourself and tell us if you got a different result from Topgrade.

Additional information:

Adding a '-v' to tmux for debbuging purposes outputs the called commands for tmux:

```
==> tmux-client-22626.log <==
1618514975.156154 sending message 106 to peer 0x7fc150008000 (0 bytes)
1618514975.156174 cmd_pack_argv: argv[0]=new-window
1618514975.156181 cmd_pack_argv: argv[1]=-a
1618514975.156188 cmd_pack_argv: argv[2]=-t
1618514975.156194 cmd_pack_argv: argv[3]=topgrade:1
1618514975.156201 cmd_pack_argv: argv[4]=ssh -t flexo env TOPGRADE_PREFIX=flexo $SHELL -lc topgrade --keep
1618514975.156216 sending message 200 to peer 0x7fc150008000 (98 bytes)
1618514975.156225 client loop enter
1618514975.166874 peer 0x7fc150008000 message 203
1618514975.166907 client loop exit
```

Even activating `assume_yes` without activating tmux generates an error - but it does not do so if I use `-y`.

I would assume the problem lies in using fish as the default shell for my machines
It used to work in a quite old version (This broke around 2021)

### PR DESCRIPTION
**Pull request by 9999years**
Fixes #107. @derphilipp would you be able to test this patch?

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself

### CODE REVIEW

**Comment by DottoDev** [comment]
Could you set this PR to merge with the bug-fix branch

**Comment by derphilipp** [comment]
@9999years Unfortunately it does not work (yet) - the connection still closes like before

**Comment by 9999years** [comment]
Yeah can you post the output of `cargo run -- -v` (on this branch). (Do you have `cargo` installed?)

**Comment by derphilipp** [comment]
Inside tmux it shows:

```
2022-11-04T11:43:57.926Z DEBUG topgrade::config > Configuration at /Users/phw/.config/topgrade.toml                                                                                                                   [0/0]
 2022-11-04T11:43:57.927Z DEBUG topgrade::config > Path ~/.tmux expanded to /Users/phw/.tmux
 2022-11-04T11:43:57.928Z DEBUG topgrade::config > Path ~/.fzf expanded to /Users/phw/.fzf
 2022-11-04T11:43:57.928Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: Some({}), post_commands: None, commands: None, git_repos: None, predefined_git_repos: None, disable: Some([Myrepos, Shell, Vim]), ignore_failures: Some([Cargo, Vim, Node, Winget, Containers, Rustup, DebGet]), remote_topgrades: Some(["url"]), remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: Some(false), yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, no_retry: None, run_in_tmux: Some(true), cleanup: Some(true), notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, composer: None, brew: None, linux: None, git: Some(Git { max_concurrency: Some(10), arguments: None, repos: Some(["/Users/phw/.tmux", "/Users/phw/.fzf"]), pull_predefined: Some(false) }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, enable_winget: Some(true) }), npm: None, yarn: None, vim: None, firmware: None, vagrant: None, flatpak: None, distrobox: None }
 2022-11-04T11:43:57.928Z DEBUG topgrade         > Version: 10.1.0
 2022-11-04T11:43:57.928Z DEBUG topgrade         > OS: x86_64-apple-darwin
 2022-11-04T11:43:57.928Z DEBUG topgrade         > Args { inner: ["target/debug/topgrade", "-v"] }
 2022-11-04T11:43:57.928Z DEBUG topgrade         > Binary path: Ok("/Users/phw/dev/topgrade/target/debug/topgrade")
 2022-11-04T11:43:57.928Z DEBUG topgrade         > Self Update: false
 2022-11-04T11:43:57.928Z DEBUG topgrade::utils  > Detected "/usr/local/bin/git" as "git"
 2022-11-04T11:43:57.928Z DEBUG topgrade::utils  > Cannot find "doas"
 2022-11-04T11:43:57.929Z DEBUG topgrade::utils  > Detected "/usr/bin/sudo" as "sudo"
 2022-11-04T11:43:57.929Z DEBUG topgrade::utils  > Cannot find "pwsh"
 2022-11-04T11:43:57.929Z DEBUG topgrade::utils  > Cannot find "powershell"
 2022-11-04T11:43:57.929Z DEBUG topgrade::runner > Step "Remote (url)"
 2022-11-04T11:43:57.930Z DEBUG topgrade::utils  > Detected "/usr/bin/ssh" as "ssh"
 2022-11-04T11:43:57.930Z DEBUG topgrade::utils  > Detected "/usr/local/bin/tmux" as "tmux"
 2022-11-04T11:43:57.948Z DEBUG topgrade::runner > Step "Brew (ARM)"
 2022-11-04T11:43:57.948Z DEBUG topgrade::runner > Step "Brew (Intel)"
 2022-11-04T11:43:57.948Z DEBUG topgrade::utils  > Detected "/usr/local/bin/brew" as "/usr/local/bin/brew"

―― 12:43:57 - Brew ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2022-11-04T11:43:57.949Z DEBUG topgrade::executor > Running "/usr/local/bin/brew" "update"
Already up-to-date.
 2022-11-04T11:44:02.696Z DEBUG topgrade::executor > Running "/usr/local/bin/brew" "upgrade" "--ignore-pinned" "--formula"
 2022-11-04T11:44:08.221Z DEBUG topgrade::executor > Running "/usr/local/bin/brew" "cleanup"
....
```
(I left the rest of the output, as it just shows the ususal commands that run perfectly fine locally)

The session on the host 'url' closed almost immediately;
If this of concern: tmux is located on the host system (tim) in `/usr/local/bin/tmux` on the remote computer in `/usr/bin/tmux`

**Pull request merged**
