### PR TITLE
10.2.0 release 

### PR DESCRIPTION
**Pull request by DottoDev**
Review of code is imo not necessary, but I would still need someone to give his okay for this merge and the creation of a release following this PR.

### CODE REVIEW

**Comment by pan93412** [comment]
As that is a relatively large PR, I may not be able to review it recently (at least this day) Sorry :(

**Comment by DottoDev** [comment]
All the code has already been review it's just that someone gives an okay for a push from dev to master and to release everything as 10.2.0. No code review is required.

**Comment by guihkx** [comment]
I haven't experienced any obvious breakage locally, so LGTM.

**Comment by DottoDev** [comment]
@guihkx thanks

**Pull request merged**
