### PR TITLE
Enhance the README

### PR DESCRIPTION
**Pull request by paescuj**
- Center logo and demo and make them a bit smaller so visitors have to scroll down a bit less
- Rename "Fork" section to "Introduction" and use note box to separate info from actual content
- Adjust links to packages
- Some formatting improvements

Also I think it would be great to be consistent in the casing of "topgrade" (capital letter vs lower case letter), for example:
- https://github.com/topgrade-rs/topgrade/blob/639c7fd422447342f81ae1d25bce647a99a29b48/README.md?plain=1#L12
- https://github.com/topgrade-rs/topgrade/blob/639c7fd422447342f81ae1d25bce647a99a29b48/README.md?plain=1#L34

### CODE REVIEW

**Comment by DottoDev** [comment]
Looks great, thanks

**Comment by paescuj** [comment]
Thank you!

**Comment by paescuj** [comment]
> Also I think it would be great to be consistent in the casing of "topgrade" (capital letter vs lower case letter), for example:

@DottoDev What do you think about this? 😃

**Comment by DottoDev** [comment]
Consistency would be great, but I don't really know if topgrade or Topgrade should be used. But probably would be topgrade the better option.

**Pull request merged**
