### PR TITLE
run_custom_command: use interactive shell on unix

### PR DESCRIPTION
**Pull request by utkarshgupta137**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself
    - [x] I also tested that Topgrade skips the step where needed

Tested on macOS 13.2 (M1 Pro) with homebrew zsh.

### CODE REVIEW

**Comment by DottoDev** [comment]
What would be the advantage of running the command in an interactive shell?

**Comment by utkarshgupta137** [comment]
Aliases/functions defined in *rc file won't be available without an interactive shell

**Review by DottoDev — APPROVED** [review]

**Comment by reini-1** [comment]
topgrade now stops working on the second custom command by sending it in the background.

```shell
Ubuntu-22.04> reini@ubuntu:~$ topgrade --only custom_commands
Due to a design issue with notify-send it could be that topgrade hangs when it's finished.
If this is the case on your system add the --skip-notify flag to the topgrade command or set skip_notify = true in the config file.
If you don't want this message to appear any longer set display_preamble = false in the config file.
For more information about this issue see https://askubuntu.com/questions/110969/notify-send-ignores-timeout and https://github.com/topgrade-rs/topgrade/issues/288.

── 10:58:13 - Self update ──────────────────────────────────────────────────────
Topgrade is up-to-date

── 10:58:14 - 01 Update downloaded apps ────────────────────────────────────────
2023-03-13 10:58:14: Update as-tree
2023-03-13 10:58:15: Update bat
...
── 10:58:19 - 12 Create/update ~/.ssh/config.known_hosts ───────────────────────

[7]+  Stopped                 topgrade --only custom_commands

Ubuntu-22.04> reini@ubuntu:~$ jobs
[1]   Stopped                 topgrade
[2]   Stopped                 topgrade --only custom_commands
[3]   Stopped                 topgrade --only custom_commands
[4]-  Stopped                 topgrade --only custom_commands
[5]+  Stopped                 topgrade --only custom_commands
```

How can I fix this?

As a workaround I downgraded to the previous version. That works fine.

**Comment by utkarshgupta137** [comment]
I'm not sure this is entirely related to this PR. I also use multiple commands & don't face this issue. I'm using zsh on macOS btw.
Can you share your shell (`echo $SHELL`) & the full custom command? Does the custom command work from your normal shell?

**Comment by utkarshgupta137** [comment]
@DottoDev In hindsight, this was a breaking change and should've been a minor version bump at least. Feel free to revert it, I'll work on a configurable version in the meanwhile.

**Comment by reini-1** [comment]
See also https://github.com/topgrade-rs/topgrade/issues/380

**Comment by DottoDev** [comment]
Will be reverted rn and 1 new feature will be added

**Pull request merged**
