### PR TITLE
Add `Sudo` type

### PR DESCRIPTION
**Pull request by 9999years**
This is a general refactor and improves on #219 for non-`sudo` sudos

### CODE REVIEW

**Comment by ercan1104** [comment]
How to build it?
```
error[E0432]: unresolved import `crate::utils::sudo`
  --> src/steps/node.rs:18:5
   |
18 | use crate::utils::sudo;
   |     ^^^^^^^^^^^^^^^^^^ no `sudo` in `utils`
```

**Comment by 9999years** [comment]
Oops, sorry. Fixed the build.

**Review by DottoDev — APPROVED** [review]
Looks good but fixing the failing checks is required before a merge. See CI Results for more information.

**Review by DottoDev — CHANGES_REQUESTED** [review]
Looks good but fixing the failing checks is required before a merge. See CI Results for more information.

**Review by DottoDev — APPROVED** [review]

**Pull request merged**
