### PR TITLE
fix: Handle '# [include]'. Update default config

### PR DESCRIPTION
**Pull request by slowsage**
Default config will now work (with commented out include section).

## Standards checklist:

- [x] The PR title is descriptive.
- [x] I have read `CONTRIBUTING.md`
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself
    - [x] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by SteveLauC** [comment]
In `config.rs`, almost every other types take `Option<>` field, IMHO, it would be better to make [`struct Include`](https://github.com/topgrade-rs/topgrade/blob/f6e8af186c76e742784557d6cf324377f715f5fd/src/config.rs#L200-L203) take `Option<Vec<String>>`, but this needs some extra work to be done as [Merge](https://docs.rs/merge/latest/merge/)(crate used to handle the file merging logic) does not support merge `Option<Vec<T>>`

```rust
pub struct Include {
    paths: Option<Vec<String>>,
}
```

@slowsage Would u like to implement this in this PR, if not, leaving it as is is still good enough to me:)

**Review by DottoDev — APPROVED** [review]

**Comment by slowsage** [comment]
Vagrant has:
```
pub struct Vagrant {
    #[merge(strategy = crate::utils::merge_strategies::vec_prepend_opt)]
    directories: Option<Vec<String>>,

    power_on: Option<bool>,
    always_suspend: Option<bool>,
}
```
I can take a crack if vec_prepend_opt is the way.

**Comment by DottoDev** [comment]
Is it ready to be merged?

**Comment by slowsage** [comment]
Tested it with paths as optional. Please confirm that I did the unwrap appropriately. Thank you!

**Comment by SteveLauC** [comment]
LGTM! Thanks

**Review by DottoDev — APPROVED** [review]

**Pull request merged**
