### PR TITLE
Fix tmux panic

### LINKED ISSUE #107: tmux + ssh + fish breaks. $SHELL gets evaluated locally / escaping problems?
**What did you expect to happen?**

Executing my upgrades for other machines works, unless I start using them inside tmux.

Having them as a dry-run exposes (for example):
`/usr/bin/ssh -t flexo env TOPGRADE_PREFIX=flexo $SHELL -lc topgrade`

**What actually happened?**
The remote side gives back an error:
```
env: ‘/usr/local/bin/fish’: No such file or directory
```

But of course that cannot be executed like that: Although locally there is a `/usr/local/bin/fish` - no such thing exists remotely. The remote shell would be `/usr/bin/fish` (and is set as a default anyway).

So I guess `$SHELL` shouldn't be evaluated **locally** - so if I escape it manually (on the commandline) to be...

```
/usr/bin/ssh -t flexo env TOPGRADE_PREFIX=flexo '$SHELL' -lc topgrade
```

(pay attention to the single quotes around `$SHELL`)
... it works.

Now another error occurs if we have the `yes` flag activated, as it tries to run, but fails being unable to parse the commandline correctly. Weird.

Again, if I escape the given commandline to:

(Before)
```
/usr/bin/ssh -t flexo env TOPGRADE_PREFIX=flexo $SHELL -lc topgrade -y
```

(After)
```
/usr/bin/ssh -t flexo env TOPGRADE_PREFIX=flexo '$SHELL' -lc topgrade\ -y
```

it works.

**Additional details:**

*Which operating system or Linux distribution are you using?*
    macOS, from here trying to connect to multiple Linux hosts of different flavors. They all behave the same.
**How did you install Topgrade?**
    * Manually downloaded and placed in /usr/local/bin (linux) or ~/bin/topgrade (macos)
    * Installting via Homebrew
    * Manually compiling

Run topgrade --dry-run to see which commands Topgrade is running. If the command seems wrong and you know why pleaes tell us so.
If the command seems fine try to run it yourself and tell us if you got a different result from Topgrade.

Additional information:

Adding a '-v' to tmux for debbuging purposes outputs the called commands for tmux:

```
==> tmux-client-22626.log <==
1618514975.156154 sending message 106 to peer 0x7fc150008000 (0 bytes)
1618514975.156174 cmd_pack_argv: argv[0]=new-window
1618514975.156181 cmd_pack_argv: argv[1]=-a
1618514975.156188 cmd_pack_argv: argv[2]=-t
1618514975.156194 cmd_pack_argv: argv[3]=topgrade:1
1618514975.156201 cmd_pack_argv: argv[4]=ssh -t flexo env TOPGRADE_PREFIX=flexo $SHELL -lc topgrade --keep
1618514975.156216 sending message 200 to peer 0x7fc150008000 (98 bytes)
1618514975.156225 client loop enter
1618514975.166874 peer 0x7fc150008000 message 203
1618514975.166907 client loop exit
```

Even activating `assume_yes` without activating tmux generates an error - but it does not do so if I use `-y`.

I would assume the problem lies in using fish as the default shell for my machines
It used to work in a quite old version (This broke around 2021)

### LINKED ISSUE #117: Panic with `--tmux` when tmux is already running
```ShellSession
$ cargo run -- --tmux
create window failed: index 0 in use
thread 'main' panicked at 'Error running Topgrade in tmux: exit status: 1', src/steps/tmux.rs:95:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

On latest `master` (a7c22625378a13a318624da3817c740a395e2736)

### PR DESCRIPTION
**Pull request by 9999years**
Fixes #117. Might fix #107 -- @derphilipp can you try this patch with the tmux-remote-ssh feature? (`run_in_tmux` + `remote_topgrades`)

### CODE REVIEW

**Comment by derphilipp** [comment]
The spawning of windows seems to work, although the sessions themselfes don't connect to the remote / get closed quite fast so I cannot see any result/whats running in there;

**Comment by 9999years** [comment]
> The spawning of windows seems to work

That's great, thanks!

```
Executing command `/usr/local/bin/tmux new-session -d -s topgrade-1 -n url 'ssh -t url env '\''TOPGRADE_PREFIX=url'\'' '\''$SHELL'\'' -lc topgrade --keep'`
```

This looks correct, too, and I think `$SHELL` is getting quoted correctly.

> the sessions themselfes don't connect to the remote / get closed quite fast

This is less good, I'll see if I can figure out why they're getting closed.

**Comment by DottoDev** [comment]
@derphilipp could you test it again?

**Comment by derphilipp** [comment]
It seems it still is not behaving like it should - no difference to the last changes; Should the outptu commands be evaulated by shell?
Because running
```
﻿ssh -t flexo env '\''TOPGRADE_PREFIX=flexo'\'' '\''$SHELL'\'' -lc topgrade
```
manually results in the Shell seemingly still being evaluated locally (as my local SHELL is in a different path than the one on `flexo`, it breaks:

```
env: ‘/usr/local/bin/fish’: No such file or directory
Connection to 192.168.1.32 closed.
```

If I manually insert the path of the shell, it seems to work:
```
ssh -t flexo env '\''TOPGRADE_PREFIX=flexo'\'' '\''/usr/bin/fish'\'' -lc topgrade
```

**Comment by derphilipp** [comment]
It seems it still evalutes `$SHELL` locally:

```
env: ‘/usr/local/bin/fish’: No such file or directory
Connection to 192.168.1.32 closed.
```

The mentioned path of`fish` is the one on the computer I use to start topgrade, not on the target device (macos vs. linux)

```/usr/local/bin/fish``` (starting macos device)  vs. ```/usr/bin/fish``` ("target" linux device)

**Comment by DottoDev** [comment]
I will review it.

**Review by DottoDev — APPROVED** [review]

**Pull request merged**
