### PR TITLE
Added Bun packages step

### PR DESCRIPTION
**Pull request by LeSnake04**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] I have read `CONTRIBUTING.md`
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself
 
## For new steps
- [x] *Optional:* Topgrade skips this step where needed
- [ ] *Optional:* The `--dry-run` option works with this step
- [ ] *Optional:* The `--yes` option works with this step if it is supported by 
  the underlying command  (N/A: no confirmation dialog)

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

## Notes
Bun has a --dry-run command but it lists all installed packages so its output is probably too verbose to be useful for most users.

PS: I triple checked that I didn't forget the require call this time.

### CODE REVIEW

**Review by SteveLauC — APPROVED** [review]

**Comment by SteveLauC** [comment]
Thanks! :)

**Comment by JakobFels** [comment]
This step fails if there are no packages installed globally (but bun is installed)

```
bun -g update
No package.json, so nothing to update
```

**Comment by JakobFels** [comment]
The step should probably check if 
`~/.bun/install/global/package.json` exists

**Comment by LeSnake04** [comment]
fixed it #617

**Pull request merged**
