### PR TITLE
feat: support waydroid

### LINKED ISSUE #684: Support for `waydroid`'s image upgrade
### Which tool is this about? Where is its repository?
[Waydroid](https://waydro.id/) is a container-based tool to boot a full Android system on a regular GNU/Linux system (i.e. an Android simulator). It uses Linux namespaces (user, pid, uts, net, mount, ipc) and provides Android applications on any GNU/Linux-based platform.

The Android runtime environment ships with a minimal customized Android system image based on [LineageOS](https://lineageos.org/), which receives frequent (weekly) upgrades. 

[Repository](https://github.com/waydroid/waydroid/).

### Which operating systems are supported by this tool?

Any x86_64 GNU/Linux with Wayland session and kernel module `binder_linux`.

### What should Topgrade do to figure out if the tool needs to be invoked?
`waydroid` executable exists and `$ waydroid status` exits successfully.

### Which exact commands should Topgrade run?
`# waydroid upgrade`, which stops running containers, downloads new images (if any) and extracts them.

Since it will kill any running containers without confirmation, one can use `$ waydroid status` to determine whether the container is running first, and allow user to save their work.

Running:

```
$ waydroid status
Session:        RUNNING
Container:      RUNNING
Vendor type:    MAINLINE
IP address:     192.168.240.112
Session user:   w568w(1000)
Wayland display:        wayland-0
```

Stopped:

```
$ waydroid status 
Session:        STOPPED
Vendor type:    MAINLINE
```

### PR DESCRIPTION
**Pull request by SteveLauC**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] I have read `CONTRIBUTING.md`
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
 
## For new steps
- [x] *Optional:* Topgrade skips this step where needed
- [ ] *Optional:* The `--dry-run` option works with this step
- [ ] *Optional:* The `--yes` option works with this step if it is supported by 
  the underlying command

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

## What does this PR do

Support a new step Waydroid, closes #684.

### CODE REVIEW

**Comment by SteveLauC** [comment]
[Here](https://github.com/SteveLauC/topgrade/releases/tag/pr687) is a build for `x86_64-unknown-linux-musl`, @w568w, welcome to give it a test:

1. The `--dry-run` option works with this step:

    ```sh
    $ ./topgrade --only waydroid --dry-run
    ```

2. The `--yes` option works with this step:
    
    1. Make sure the container is running, then
       
        > You should not enable assume yes in your config file
     
         ```sh
         $ ./topgrade --only waydroid
         ```
      
         You should receive a prompt asking if you want to do the update:

         > Going to execute `waydroid update`, which would STOP the running container, is this ok?

    3. Make sure the container is running, and the `--yes` option is passed (or it is enabled in your config file):
        
        ```sh
        $ ./topgrade --only waydroid --yes
        ```

        That prompt should not appear.

**Comment by w568w** [comment]
Thanks for your work! 

Container detection works well, but I think you need root access to run `# waydroid upgrade`, as I stated in #684:

```
$ ./topgrade --only waydroid 

── 21:56:36 - Sudo ─────────────────────────────────────────────────────────────
Going to execute `waydroid update`, which would STOP the running container, is this ok? (y)es/(N)o y
── 21:56:42 - Waydroid ─────────────────────────────────────────────────────────
[21:56:43] ERROR: Action "upgrade" needs root access
[21:56:43] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
Waydroid failed: 
   0: Command failed: `/usr/bin/waydroid upgrade`
   1: `/usr/bin/waydroid` failed: exit status: 1

Location:
   src/steps/os/linux.rs:1060
Retry? (y)es/(N)o/(s)hell/(q)uit
```

**Comment by SteveLauC** [comment]
1. you need root access to run # waydroid upgrade
2. there is a typo in message Going to execute waydroid update..., which should be waydroid upgrade.

They are fixed, and I adjusted the location of the separator so that the prompt won't be printed before it:

> Going to execute `waydroid update`, which would STOP the running container, is this ok? (y)es/(N)o y
> ── 21:56:42 - Waydroid ─────────────────────────────────────────────────────────


-----

[Binary](https://github.com/SteveLauC/topgrade/releases/tag/pr687) updated, welcome to give it another try.

**Comment by w568w** [comment]
Confirmed that it works. Thanks!

```
$ ./topgrade --only waydroid
── 10:30:25 - Sudo ─────────────────────────────────────────────────────────────

── 10:30:25 - Waydroid ─────────────────────────────────────────────────────────
Going to execute `waydroid upgrade`, which would STOP the running container, is this ok? (y)es/(N)o [y] [10:30:26] Stopping container
[10:30:32] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240210-VANILLA-waydroid_x86_64-system.zip/download
[Downloading] 769.39 MB/769.43 MB     2903.3 kbps(approx.)[10:35:49] Validating system image
[10:35:50] Extracting to /var/lib/waydroid/images
[10:38:13] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20240210-MAINLINE-waydroid_x86_64-vendor.zip/download
[Downloading] 180.62 MB/180.62 MB    11439.41 kbps(approx.)[10:41:15] Validating vendor image
[10:41:15] Extracting to /var/lib/waydroid/images
 
── 10:41:18 - Summary ──────────────────────────────────────────────────────────
Waydroid: OK
```

**Pull request merged**
