### PR TITLE
Run `fisher` if `fish -c 'type -t fisher'` is OK

### PR DESCRIPTION
**Pull request by 9999years**
Fixes https://github.com/topgrade-rs/topgrade/issues/9

It definitely works, although if you just install `fisher` (e.g. with `brew install fisher`) and don't do anything else, it's not too happy:

```
―― 22:07:34 - Fisher ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
fisher: "/Users/wiggles/.config/fish/fish_plugins" file not found: "update"

Retry? (y)es/(N)o/(s)hell/(q)uit
```

I think `~/.config/fish/fish_plugins` is where `fisher` expects to find a list of plugins. I don't use `fisher` currently, though.

### CODE REVIEW

**Comment by 9999years** [comment]
Maybe it should check if `fish_plugins` exists instead... @Chrobin111 @phnx47 what do you think?

**Comment by Chrobin111** [comment]
This file does exist for me and contains all plugins. So this works, at least for me.

**Comment by 9999years** [comment]
Is there an environment variable you can set to have a different `fish_plugins` path?

**Comment by 9999years** [comment]
For future me: it's [`$__fish_config_dir/fish_plugins`](https://github.com/jorgebucaran/fisher/tree/36810b39401536650d7a1018c8f3832f51741950#using-your-fish_plugins-file), apparently.

**Comment by DottoDev** [comment]
> For future me: it's `$__fish_config_dir/fish_plugins`apparently.

That's what I call a variable name xD

**Comment by phnx47** [comment]
It is always `$__fish_config_dir/fish_plugins` https://github.com/jorgebucaran/fisher/blob/36810b39401536650d7a1018c8f3832f51741950/functions/fisher.fish#L4.

Sometimes fish config can be synchronized between machines, but fisher not installed in each of them. 
I think that best way: check with command `fish -c 'type -t fisher'`, then check `$__fish_config_dir/fish_plugins`.

**Comment by 9999years** [comment]
Done; now it checks that `type -t fisher` works and that the `fisher_path` exists.

**Comment by DottoDev** [comment]
Mergeable now?

**Review by DottoDev — APPROVED** [review]

**Review by DottoDev — APPROVED** [review]

**Comment by 9999years** [comment]
Yeah I think this is ready for merge.

**Pull request merged**
