### PR TITLE
fix: tmux unknown cmd: attach-client

### LINKED ISSUE #928: unknown command: attach-client
## Erroneous Behavior

```sh
# topgrade
unknown command: attach-client
```

## Expected Behavior
Just run

## Steps to reproduce
```ini
# ~/.config/topgrade.d/overwrites.toml
[misc]

run_in_tmux = true
skip_notify = true
only = ["self_update", "system", "flatpak", "firmware"]
```

## Problem persists without calling from topgrade

- [ ] Yes
- [X] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [X] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [ ] Yes
- [ ] No

## Configuration file (Optional)

```toml
[misc]

run_in_tmux = true
tmux_session_mode = "attach_if_not_in_session"
skip_notify = true
only = ["self_update", "system", "flatpak", "firmware"]
```

## Additional Details
- Operation System/Version: Fedora 40
- Installation: GitHub release
- Topgrade version (`topgrade -V`): 16.0.0

## Verbose Output (`topgrade -v`)

<details>
<pre>
root@localhost:~# topgrade -vt
DEBUG Current system locale is en-US
DEBUG Found additional (directory) configuration file at /root/.config/topgrade.d/overwrites.toml
DEBUG Version: 16.0.0
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "-vt"] }
DEBUG Binary path: Ok("/usr/local/bin/topgrade")
DEBUG self-update Feature Enabled: true
DEBUG Configuration: Config { opt: CommandLineArgs { edit_config: false, show_config_reference: false, run_in_tmux: true, cleanup: false, dry_run: false, no_retry: false, disable: [], only: [], custom_commands: [], env: [], verbose: true, keep_at_end: false, skip_notify: false, yes: None, disable_predefined_git_repos: false, config: None, remote_host_limit: None, show_skipped: false, log_filter: "warn", gen_completion: None, gen_manpage: false, no_self_update: false }, config_file: ConfigFile { include: None, misc: Some(Misc { pre_sudo: None, sudo_command: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, no_retry: None, run_in_tmux: None, tmux_session_mode: Some(AttachIfNotInSession), cleanup: None, notify_each_step: None, skip_notify: Some(true), bashit_branch: None, only: Some([SelfUpdate, System, Flatpak, Firmware]), no_self_update: None, log_filters: None }), pre_commands: None, post_commands: None, commands: None, python: None, composer: None, brew: None, linux: None, git: None, containers: None, windows: None, npm: None, yarn: None, vim: None, firmware: None, vagrant: None, flatpak: None, distrobox: None, lensfun: None }, allowed_steps: [SelfUpdate, System, Flatpak, Firmware] }
DEBUG Detected "/usr/bin/tmux" as "tmux"
DEBUG Executing command `/usr/bin/tmux has-session -t topgrade`
DEBUG Executing command `/usr/bin/tmux has-session -t topgrade-1`
DEBUG Executing command `/usr/bin/tmux has-session -t topgrade-2`
DEBUG Executing command `/usr/bin/tmux has-session -t topgrade-3`
DEBUG Executing command `/usr/bin/tmux has-session -t topgrade-4`
DEBUG Executing command `/usr/bin/tmux has-session -t topgrade-5`
DEBUG Executing command `/usr/bin/tmux has-session -t topgrade-6`
DEBUG Executing command `/usr/bin/tmux new-session -d -s topgrade-6 -n topgrade 'env '\''TOPGRADE_KEEP_END=1'\'' '\''TOPGRADE_INSIDE_TMUX=1'\'' topgrade -vt'`
unknown command: attach-client
</pre>
</details>

### PR DESCRIPTION
**Pull request by SteveLauC**
## What does this PR do

Based on [this comment](https://github.com/topgrade-rs/topgrade/issues/928#issuecomment-2396639729), fixes #928.

## Standards checklist

- [x] The PR title is descriptive.
- [x] I have read `CONTRIBUTING.md`
- [ ] *Optional:* I have tested the code myself
 
## For new steps

- [ ] *Optional:* Topgrade skips this step where needed
- [ ] *Optional:* The `--dry-run` option works with this step
- [ ] *Optional:* The `--yes` option works with this step if it is supported by 
  the underlying command

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by SteveLauC** [comment]
[Here](https://github.com/SteveLauC/topgrade/releases/tag/pr937) is a build of Topgrade with this patch included, cc @rabin-io @lucaspar, could you guys please give it a test?

**Comment by rabin-io** [comment]
@SteveLauC looks good from my end, works with my current config (as above).

**Review by lucaspar — APPROVED** [review]
:+1:

**Comment by SteveLauC** [comment]
Thanks for testing it!

**Pull request merged**
