### PR TITLE
Add unstable feature with distrobox support

### PR DESCRIPTION
**Pull request by DottoDev**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by 9999years** [comment]
Any reason to gate this behind a feature flag?

**Comment by DottoDev** [comment]
Yes, distrobox current makes too many problems, I probably missed something in the implementation but I can't find it. So after discussion in #163 I put it behind a feature flag for now. Also I would love to put new "untested" features behind it just to not break the widely distributed versions.

**Review by pan93412 — COMMENTED** [review]
It may be better to separate 'distrobox' as a feature, and makes 'unstable' the meta feature. For example:

```toml
distrobox = []
unstable = ["distrobox"]
```

Thus, users are able to customize which unstable features they want to enable.

**Comment by DottoDev** [comment]
Good point, this makes more sense

**Comment by LeSnake04** [comment]
Now that #163 is resolved, is there any other problem with distrobox? 

I will try my best to adress it.

**Comment by LeSnake04** [comment]
Alternatively make a --unstable flag that activates untested features. 

Then ask users in the release notes to enable the flag for testing and to report issues when unstable steps added. 

When no issues reportet for a feature enable it globally

**Comment by dylanmtaylor** [comment]
I don't think this is necessary - seems to have no issues on master.

**Comment by DottoDev** [comment]
Because now it seems like that it works for everyone this is outdated.

**Pull request closed without merging**
