### PR TITLE
Update GitHub Actions workflow for Codecov integration

### PR DESCRIPTION
**Pull request by niStee**
- Refine the testing matrix to include only stable and nightly versions of Rust
- Add 'fail_ci_if_error' option to Codecov step for stricter CI checks
- Ensure newline at end of file

## Standards checklist:

- [x] The PR title is descriptive.
- [x] I have read `CONTRIBUTING.md`
- [ ] The code compiles (`cargo build`)
- [ ] The code passes rustfmt (`cargo fmt`)
- [ ] The code passes clippy (`cargo clippy`)
- [ ] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
 
## For new steps
- [ ] *Optional:* Topgrade skips this step where needed
- [ ] *Optional:* The `--dry-run` option works with this step
- [ ] *Optional:* The `--yes` option works with this step if it is supported by 
  the underlying command

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by niStee** [comment]
While reviewing the logs of the other PR, I noticed that the macOS Codecov report could not be uploaded due to an incorrect secret. It is strange because it uses the same workflow step, isn't it?

**Comment by SteveLauC** [comment]
> It is strange because it uses the same workflow step, isn't it?

Indeed, they all use the same token, so weird.

**Comment by niStee** [comment]
> > It is strange because it uses the same workflow step, isn't it?
> 
> Indeed, they all use the same token, so weird.

I need to sleep first. Try to debug it later.

**Comment by SteveLauC** [comment]
Seems that there are indeed some issues with the token, other checks succeed because:

> info - 2024-02-25 03:01:39,390 -- The PR is happening in a forked repo. Using tokenless upload.

**Comment by SteveLauC** [comment]
It is my fault, the token is wrong, I have corrected it.

**Pull request merged**
