### PR TITLE
CI: Update cross to v0.2.5

### PR DESCRIPTION
**Pull request by guihkx**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by DottoDev** [comment]
Does FreeBSD wotk now for cross?

**Comment by guihkx** [comment]
You mean DragonFly BSD? But no, unfortunately the fix wasn't included in 0.2.5:

https://github.com/cross-rs/cross/discussions/1165#discussioncomment-4870940

**Comment by DottoDev** [comment]
No, FreeBSD, see https://github.com/topgrade-rs/topgrade/actions/runs/4048280767/jobs/6963310839

**Comment by guihkx** [comment]
Ah, that's a known limitation for some targets... From their README:

>Testing support (`cross test`) is more complicated. It relies on [QEMU](https://www.qemu.org/) emulation, so testing may fail due to QEMU bugs rather than bugs in your crate. That said, a target has a ✓ in `test` column of the table below if it can run the [`compiler-builtins`](https://github.com/rust-lang-nursery/compiler-builtins) test suite.
>Target | libc | GCC | C++ | QEMU | test
>  -- | -- | -- | -- | -- | --
>`x86_64-unknown-freebsd` | 1.5 | 6.4.0 | ✓ | N/A |

**Pull request merged**
