### PR TITLE
chore: improve Windows Update step and add PSWindowsUpdate Module

### PR DESCRIPTION
**Pull request by niStee**
Refactor the `windows_update` function in `windows.rs` to improve the Windows Update step. Added a prompt for administrator privileges and updated the warning message. Also, added support for installing the PSWindowsUpdate Module as an alternative to using USOClient for Windows Update.

still see warning:
The installer will request to run as administrator, expect a prompt.
Start-Process : A parameter cannot be found that matches parameter name 'Command'.
At line:1 char:74
+ ... ath powershell -Verb runAs -ArgumentList  -NoProfile -Command Import- ...
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Start-Process], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.StartProcessCommand

VERBOSE: MSI-THIN-GF36 (6/30/2024 4:48:48 PM): Connecting to Microsoft Update server. Please wait...
VERBOSE: Found [0] Updates in pre search criteria

but as the verbose shows it works

## Standards checklist

- [x] The PR title is descriptive.
- [x] I have read `CONTRIBUTING.md`
- [x] *Optional:* I have tested the code myself
 
## For new steps

- [ ] *Optional:* Topgrade skips this step where needed
- [ ] *Optional:* The `--dry-run` option works with this step
- [ ] *Optional:* The `--yes` option works with this step if it is supported by 
  the underlying command

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by niStee** [comment]
Blocked by #871

**Comment by SteveLauC** [comment]
> Blocked by #871

Fixed now

**Comment by niStee** [comment]
#867

**Comment by SteveLauC** [comment]
Thanks for the patch!

cc @BoYanZh @BobG1983, could you guys give this patch a try and see if it addresses your issues?

**Comment by BoYanZh** [comment]
> Thanks for the patch!
> 
> cc @BoYanZh @BobG1983, could you guys give this patch a try and see if it addresses your issues?
> 
> If you don't have a Rust toolchain installed, I can build Topgrade with this patch in my Windows VM, but I am not familiar with Windows, if I directly send the exe file, is it executable on your machines?

I have tried it and it works! I built it with `cargo build --release --target x86_64-pc-windows-gnu; cross build --release --target x86_64-pc-windows-gnu` in my WSL.

**Comment by SteveLauC** [comment]
> I have tried it and it works! I built it with cargo build --release --target x86_64-pc-windows-gnu; cross build --release --target x86_64-pc-windows-gnu in my WSL.

Nice, thanks for testing it!

**Review by SteveLauC — APPROVED** [review]
Let's merge this PR

**Pull request merged**
