### PR TITLE
Fixes rubygems on .deb distros

### LINKED ISSUE #259: Error in rubygems when installed through APT
## What did you expect to happen?
topgrade executes all ok

## What actually happened?
rubygems fails

## Additional Details
- Which operating system or Linux distribution are you using?
Kubuntu 22.10
- How did you install Topgrade?
Through pacstall
- Which version are you running? 
10.2.2

ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.

<details>

<pre>
―― 11:54:33 - RubyGems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/gem update --system`
ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.
DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/gem update --system`
   1: `/usr/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:92

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "rubygems" failed: 
   0: Command failed: `/usr/bin/gem update --system`
   1: `/usr/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:92

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
rubygems failed: 
   0: Command failed: `/usr/bin/gem update --system`
   1: `/usr/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:92

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.DEBUG Desktop notification: rubygems failed
DEBUG Executing command `/usr/bin/notify-send -a Topgrade Topgrade 'rubygems failed'`
</pre>
</details>

I think to solve this we can do a test on /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb
if the file exists, skip the step. Or maybe do a test on the file like does it contain the error message or test the checksum. See this file which installs with APT rubygems installation https://salsa.debian.org/ruby-team/rubygems-integration/-/blob/master/lib/rubygems/defaults/operating_system.rb

### PR DESCRIPTION
**Pull request by DottoDev**
Closes #259 
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.
@Zahrun please test

### CODE REVIEW

**Comment by Zahrun** [comment]
Now I am getting this
```
―― 23:26:57 - RubyGems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Updating installed gems
Updating asciidoctor
Fetching asciidoctor-2.0.18.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/3.0.0 directory.
rubygems failed: 
   0: Command failed: `/usr/bin/gem Update`
   1: `/usr/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:95

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit
```
I think this step has to be skipped entirely since from [the reference](https://guides.rubygems.org/command-reference/#gem-update):
```
gem update

Update installed gems to the latest version
Usage

gem update GEMNAME [GEMNAME ...] [options]

Options

    --system [VERSION] - Update the RubyGems system software
```
The software itself is updated by the distribution.
The gems are updated in the `gem` step

**Comment by Zahrun** [comment]
`sudo /usr/bin/gem Update`

runs without error however, but I am not sure what that does, it seems to install many packages in a different location than the gem step

`--[no-]user-install - Install in user’s home directory instead of GEM_HOME.`

**Comment by DottoDev** [comment]
Sorry, my fault, I misunderstood how rubygems works. Will fix tomorrow. Till then you can manually disable this step

**Comment by Zahrun** [comment]
> Sorry, my fault, I misunderstood how rubygems works. Will fix tomorrow. Till then you can manually disable this step

Honestly, it is kind of confusing to me too. Thank you for pushing the fix.

**Pull request closed without merging**
