### PR TITLE
Fix nix profile upgrade command & add profile path detection

### LINKED ISSUE #34: nix: "incompatible with 'nix-env'; please use 'nix profile' instead"
Using `nix profile` will [obsolete/break `nix-env`](https://nixos.wiki/wiki/Nix_command/profile)

## What did you expect to happen?
Nix upgrade uses `nix profile` when the profile contains `manifest.json` (like [nix-env does the check](https://github.com/NixOS/nix/blob/master/src/nix-env/user-env.cc#L20)):
`/nix/var/nix/profiles/per-user/manu/profile/manifest.json`

The command that is applicable then is:
```
nix profile upgrade '.*'
```

## What actually happened?
```
―― 15:28:57 - Nix ―――――――――
this derivation will be built:
  /nix/store/bc8p7vjvhpfrgv3h12h767yv4kbw1prm-home-manager.drv
building '/nix/store/bc8p7vjvhpfrgv3h12h767yv4kbw1prm-home-manager.drv'...
unpacking channels...
error: profile '/nix/var/nix/profiles/per-user/manu/profile' is incompatible with 'nix-env'; please use 'nix profile' instead
```

## Additional Details
- OS: Fedora beta 37
- How did you install Topgrade? `cargo install topgrade-rs`
- Which version are you running? `Topgrade 9.1.0`

<pre>
Dry running: /nix/var/nix/profiles/default/bin/nix-channel --update
Dry running: /nix/var/nix/profiles/default/bin/nix-env --upgrade
</pre>

### PR DESCRIPTION
**Pull request by DottoDev**
Closes #34 
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [ ] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by dchinmay2** [comment]
This is how `/etc/profile.d/nix-daemon.sh` sets `NIX_PROFILES` (link https://github.com/NixOS/nix/blob/2b4e3fa1443c8d56ead43865adf037efa92c3fd7/scripts/nix-profile-daemon.sh.in):
```sh
NIX_LINK=$HOME/.nix-profile
if [ -n "${XDG_STATE_HOME-}" ]; then
    NIX_LINK_NEW="$XDG_STATE_HOME/nix/profile"
else
    NIX_LINK_NEW=$HOME/.local/state/nix/profile
fi
if [ -e "$NIX_LINK_NEW" ]; then
    if [ -t 2 ] && [ -e "$NIX_LINK" ]; then
        warning="\033[1;35mwarning:\033[0m"
        printf "$warning Both %s and legacy %s exist; using the former.\n" "$NIX_LINK_NEW" "$NIX_LINK" 1>&2
        if [ "$(realpath "$NIX_LINK")" = "$(realpath "$NIX_LINK_NEW")" ]; then
            printf "         Since the profiles match, you can safely delete either of them.\n" 1>&2
        else
            # This should be an exceptionally rare occasion: the only way to get it would be to
            # 1. Update to newer Nix;
            # 2. Remove .nix-profile;
            # 3. Set the $NIX_LINK_NEW to something other than the default user profile;
            # 4. Roll back to older Nix.
            # If someone did all that, they can probably figure out how to migrate the profile.
            printf "$warning Profiles do not match. You should manually migrate from %s to %s.\n" "$NIX_LINK" "$NIX_LINK_NEW" 1>&2
        fi
    fi
    NIX_LINK="$NIX_LINK_NEW"
fi

export NIX_PROFILES="/nix/var/nix/profiles/default $NIX_LINK"
```
I use `XDG_STATE_HOME`, so topgrade should check for this path too

**Comment by GideonBear** [comment]
@p00f I don't know the context, but if there's an issue, please open a new issue

**Comment by dchinmay2** [comment]
I'll make a PR fixing it later today sorry

**Comment by GideonBear** [comment]
> I'll make a PR fixing it later today sorry

np! Just make sure it's not already fixed on the main branch; we're quite a few commits behind on the latest release

**Comment by dchinmay2** [comment]
nope https://github.com/topgrade-rs/topgrade/blob/9a3ef463f92178462d44fe2e2bfb58ba46fa5b80/src/steps/os/unix.rs#L430

**Comment by dchinmay2** [comment]
#1354

**Pull request merged**
