### PR TITLE
Fix for gcloud snap issue

### LINKED ISSUE #138: If you install the Google Cloud SDK as a snap, it will throw an error every time topgrade runs
## What did you expect to happen?

Snap handles upgrades of snaps. Topgrade should ignore snap-install gcloud.

## What actually happened?

―― 23:06:18 - gcloud ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Beginning update. This process may take several minutes.
ERROR: (gcloud.components.update) You cannot perform this action because this Google Cloud CLI installation is managed by an external package manager.
Please consider using a separate installation of the Google Cloud CLI created through the default mechanism described at: https://cloud.google.com/sdk/

Retry? (y)es/(N)o/(s)hell/(q)uit

## Additional Details
- Which operating system or Linux distribution are you using? Ubuntu 22.04
- How did you install Topgrade? cargo
- Which version are you running? 

 ➜  ~ topgrade -V
Topgrade 10.0.1

<details>

<pre>

―― 23:07:24 - gcloud ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /snap/bin/gcloud components update --quiet

</pre>
</details>

### PR DESCRIPTION
**Pull request by dylanmtaylor**
Closes #138 

Since snapd handles updates for us, and it doesn't work anyways, skip if the install uses snap.

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself
    - [x] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
Clippy failure is in a file unrelated to this change.

warning: use of `unwrap_or` followed by a call to `new`
   --> src/steps/os/archlinux.rs:248:20
    |
248 |         let sudo = which("sudo").unwrap_or(PathBuf::new());
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `which("sudo").unwrap_or_default()`
    |
    = note: `#[warn(clippy::or_fun_call)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#or_fun_call

warning: `topgrade` (bin "topgrade") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 39.00s

**Comment by dylanmtaylor** [comment]
This is tested working. With this change, it properly ignores the snap-installed gcloud binary.

**Review by DottoDev — APPROVED** [review]

**Review by DottoDev — CHANGES_REQUESTED** [review]
Could you change the branch to the bug-fixes branch?

**Comment by dylanmtaylor** [comment]
> Could you change the branch to the bug-fixes branch?

I just opened #144 for you. Didn't know how to change the branch of an existing PR.

**Comment by DottoDev** [comment]
You can edit the branch too if you select edit title

**Pull request closed without merging**
